wandb_version: 1

task_id:
  desc: null
  value: 2
env_name:
  desc: null
  value: faucet-close-v2-goal-observable
nb_tasks:
  desc: null
  value: 5
state_dim:
  desc: null
  value: 39
action_dim:
  desc: null
  value: 4
hidden_dim:
  desc: null
  value: 400
num_hidden_layers:
  desc: null
  value: 2
hnet_hidden_dims:
  desc: null
  value:
  - 100
  - 100
task_emb_dim:
  desc: null
  value: 96
buffer_size:
  desc: null
  value: 2000000
batch_size:
  desc: null
  value: 1028
num_steps:
  desc: null
  value: 1000000
log_frequency:
  desc: null
  value: 2000
num_eval_episodes:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0003
learning_rate_entropy:
  desc: null
  value: 0.0003
tau:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0.99
target_update_interval:
  desc: null
  value: 2
seed:
  desc: null
  value: 0
continual:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712359898.475986
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
